BLOG_NAME = 'VeekXT'

BOOTSTRAP_SERVE_LOCAL = True
SECRET_KEY = 'sbfpiulfbsaldfvbaskgjd'

# database
DATABASE = 'postgresql://xietao:x@localhost:5432/my_blog'
SQLALCHEMY_DATABASE_URI = DATABASE
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
SQLALCHEMY_TRACK_MODIFICATIONS = False

# admin
ADMIN_NAME = 'veekxt'
ADMIN_PASSWORD = '123456'

